output:
  formats:
    - format: line-number
linters:
  enable-all: false
  disable-all: true
  enable:
    - govet
    - goimports
    - thelper
    - tparallel
    - unconvert
    - wastedassign
    - revive
    - unused
    - gofmt
    - whitespace
    - misspell
linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
severity:
  default-severity: error
