version: "2"
formatters:
  enable:
    - goimports
    - gofmt
linters:
  disable:
    - errcheck
  enable:
    - govet
    - thelper
    - tparallel
    - unconvert
    - wastedassign
    - revive
    - unused
    - whitespace
    - misspell
  settings:
    revive:
      severity: warning
